name: zhangxin
channels:
  - defaults
dependencies:
  - aiohttp=3.8.3=py38h2bbff1b_0
  - async-timeout=4.0.2=py38haa95532_0
  - blas=1.0=mkl
  - blinker=1.4=py38haa95532_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2022.10.11=haa95532_0
  - cffi=1.15.1=py38h2bbff1b_3
  - cryptography=38.0.1=py38h21b164f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - freetype=2.10.4=hd328e21_0
  - frozenlist=1.3.3=py38h2bbff1b_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=4.11.3=py38haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - kiwisolver=1.4.2=py38hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h23ce68f_0
  - libtiff=4.2.0=he0120a3_1
  - lz4-c=1.9.3=h2bbff1b_1
  - matplotlib=3.5.1=py38haa95532_1
  - matplotlib-base=3.5.1=py38hd77b12b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - munkres=1.1.4=py_0
  - numpy-base=1.22.3=py38hca35cd5_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pip=21.2.2=py38haa95532_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38haa95532_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.9.2=py38hd77b12b_6
  - pyreadline=2.1=py38_1
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - sip=4.19.13=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=h2bbff1b_0
  - tensorboard=2.9.0=py38haa95532_0
  - tensorboard-plugin-wit=1.8.1=py38haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.1=py38h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - xz=5.2.5=h8cc25b3_1
  - zipp=3.8.0=py38haa95532_0
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - aiosignal==1.3.1
    - astunparse==1.6.3
    - atomicwrites==1.4.0
    - attr==0.3.1
    - attrs==21.4.0
    - backcall==0.2.0
    - cachetools==5.0.0
    - certifi==2021.10.8
    - chardet==4.0.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - colorama==0.4.4
    - config==0.5.1
    - coremltools==4.0
    - cupy-cuda113==10.4.0
    - cython==0.29.28
    - docker-pycreds==0.4.0
    - einops==0.5.0
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - fastrlock==0.8
    - flatbuffers==1.12
    - fonttools==4.33.3
    - fsspec==2022.11.0
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.1
    - h5py==3.6.0
    - idna==3.3
    - iniconfig==1.1.1
    - ipython-genutils==0.2.0
    - joblib==1.1.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - labelimg==1.8.6
    - libclang==14.0.1
    - lightning-utilities==0.4.2
    - loguru==0.6.0
    - lxml==4.8.0
    - markdown==3.3.7
    - mistune==0.8.4
    - mpmath==1.2.1
    - multidict==6.0.3
    - ninja==1.11.1
    - numpy==1.21.5
    - oauthlib==3.2.0
    - onnx==1.8.1
    - onnx-simplifier==0.3.5
    - onnxoptimizer==0.3.2
    - onnxruntime==1.8.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pluggy==1.0.0
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.6
    - pycocotools-windows==2.0.0.2
    - pygments==2.12.0
    - pymysql==1.0.2
    - pynvrtc==9.2
    - pyparsing==3.0.9
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.10.1
    - pyrsistent==0.18.1
    - pytest==7.1.2
    - pytorch-lightning==1.8.4.post0
    - pytz==2022.1
    - pywin32==304
    - pywinpty==2.0.6
    - pyyaml==6.0
    - pyzmq==23.2.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scipy==1.8.0
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - setuptools==59.5.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - sympy==1.10.1
    - tabulate==0.9.0
    - tensorboard-data-server==0.6.1
    - tensorboardx==2.5.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - thop==0.1.1-2209072238
    - tinycss2==1.1.1
    - tomli==2.0.1
    - torch==1.10.0+cu113
    - torchaudio==0.10.0+cu113
    - torchmetrics==0.11.0
    - torchvision==0.11.1+cu113
    - tqdm==4.64.0
    - traitlets==5.3.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - wandb==0.12.17
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.1.2
    - win32-setctime==1.1.0
    - wrapt==1.14.1
    - yarl==1.8.2
prefix: E:\anaconda3\envs\zhangxin
[0m[0m