wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1678197175
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      4: 3.8.5
      5: 0.12.17
      8:
      - 3
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 32
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: F:\CVPR\yolov5-master\models\yolov5n.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: F:\CVPR\yolov5-master\data\VOC.yaml
data_dict:
  desc: null
  value:
    names:
      '0': aeroplane
      '1': bicycle
      '10': diningtable
      '11': dog
      '12': horse
      '13': motorbike
      '14': person
      '15': pottedplant
      '16': sheep
      '17': sofa
      '18': train
      '19': tvmonitor
      '2': bird
      '3': boat
      '4': bottle
      '5': bus
      '6': car
      '7': cat
      '8': chair
      '9': cow
    nc: 20
    path: F:/VOC2007txt
    test: F:\VOC2007txt\images\test
    train: F:\VOC2007txt\images\train
    val: F:\VOC2007txt\images\val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.01
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs\train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\exp
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: ''
workers:
  desc: null
  value: 8
